# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: instagram_scraper_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: instagram_scraper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./migrations/0000_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 512m
    cpus: 1.0

  android:
    image: budtmo/docker-android:emulator_11.0
    container_name: android_emulator
    # restart: unless-stopped
    devices:
      - /dev/kvm
    ports:
      - "6080:6080"
      - "4723:4723"
      - "5554:5554"
      - "5555:5555"
    environment:
      - DEBUG=true
      - EMULATOR_DEVICE=Nexus S
      - WEB_VNC=true
      - APPIUM=true
      - DEVICE_NAME=emulator-5554
      - DATAPARTITION=1g
      - EMULATOR_ARGS=-no-window -noaudio -no-boot-anim -accel on -skin 480x800 -memory 4096 -cores 3
      - CLEAN_START=false 
    volumes:
      - ./apks:/apks
      - android_data:/data
      - ./snapshots:/snapshots
      # Монтируем скрипты
      - ./scripts:/scripts:ro

    entrypoint: ["/bin/bash", "/scripts/entrypoint-wrapper.sh"]
    command: []
    privileged: true
    user: "0:0"
    stop_grace_period: 30s  # Даем время на сохранение снапшота
    healthcheck:
      test: ["CMD-SHELL", "adb devices | grep emulator-5554 | grep device"]
      interval: 10s
      timeout: 5s
      retries: 30
    mem_limit: 4g
    cpus: 3.0

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram_scraper_app_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/instagram_scraper
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANDROID_HOST=android
      - ANDROID_PORT=4723
      - ANDROID_DEVICE_NAME=Nexus S
    depends_on:
      postgres:
        condition: service_healthy
      android:
        condition: service_healthy
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/node_modules
    stdin_open: true
    tty: true
    mem_limit: 2g
    cpus: 1.0

volumes:
  postgres_data_dev:
  android_data:

networks:
  default:
    name: instagram_scraper_dev_network