services:
  postgres:
    image: postgres:15
    container_name: instagram_scraper_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: instagram_scraper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./migrations/0000_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 512m
    cpus: 1.0

  android:
    image: budtmo/docker-android:emulator_11.0
    container_name: android_emulator
    devices:
      - /dev/kvm
    ports:
      - "6080:6080"
      - "4723:4723"
      - "5554:5554"
      - "5555:5555"
    environment:
      - DEBUG=true
      - EMULATOR_DEVICE=Nexus S
      - WEB_VNC=true
      - APPIUM=true
      - DEVICE_NAME=emulator-5554
      - DATAPARTITION=4g  # Увеличиваем раздел данных для приложений
      - EMULATOR_ARGS=-no-window -noaudio -no-boot-anim -accel on -skin 480x800 -memory 4096 -cores 2 -writable-system
    volumes:
      - ./apks:/apks
      - ./android_userdata:/home/androidusr/.android
      - ./android_emulator:/home/androidusr/emulator
      - ./scripts/init-emulator.sh:/init-emulator.sh:ro
    privileged: true
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      # Восстанавливаем права
      chown -R androidusr:androidusr /home/androidusr/.android 2>/dev/null || true
      chown -R androidusr:androidusr /home/androidusr/emulator 2>/dev/null || true
      
      # Очищаем возможные lock файлы от предыдущего запуска
      rm -f /home/androidusr/emulator/*.lock 2>/dev/null || true
      rm -f /tmp/android-*.lock 2>/dev/null || true
      
      # Запускаем оригинальный entrypoint
      exec /home/androidusr/docker-android/mixins/scripts/run.sh
      "
    healthcheck:
      test: ["CMD-SHELL", "adb devices | grep emulator-5554 | grep device"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    mem_limit: 4g
    cpus: 3.0

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram_scraper_app_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/instagram_scraper
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANDROID_HOST=android
      - ANDROID_PORT=4723
      - ANDROID_DEVICE_NAME=Nexus S
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/node_modules
    stdin_open: true
    tty: true
    mem_limit: 2g
    cpus: 1.0

volumes:
  postgres_data_dev:

networks:
  default:
    name: instagram_scraper_dev_network