version: '3.8'

# Конфигурация для разработки
services:
  # PostgreSQL Database для разработки
  postgres-dev:
    image: postgres:15
    container_name: instagram_scraper_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: instagram_scraper_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Другой порт для избежания конфликтов
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Chrome Browser для разработки
  chrome-dev:
    image: browserless/chrome:latest
    container_name: instagram_scraper_chrome_dev
    restart: unless-stopped
    ports:
      - "9223:3000"  # Другой порт для разработки
    environment:
      - CONNECTION_TIMEOUT=60000
      - MAX_CONCURRENT_SESSIONS=1
      - ENABLE_DEBUGGER=true
      - CHROME_REFRESH_TIME=86400000
    shm_size: 1gb
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/json"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
    driver: local

networks:
  default:
    name: instagram_scraper_dev_network