services:
  postgres:
    image: postgres:15
    container_name: instagram_scraper_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: instagram_scraper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  android:
    image: budtmo/docker-android:emulator_11.0
    container_name: android_emulator
    privileged: true
    restart: unless-stopped
    devices:
      - /dev/kvm
    ports:
      - "6080:6080"
      - "4723:4723"
      - "5554:5554"
      - "5555:5555"
    environment:
      - EMULATOR_DEVICE=Nexus 5
      - WEB_VNC=true
      - APPIUM=true
      - DEVICE_NAME=emulator-5554
      - DATAPARTITION=2g
      - EMULATOR_ARGS="-no-snapshot-save -noaudio -no-boot-anim"
    volumes:
      - ./apks:/apks
      - android_data:/data
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram_scraper_app_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/instagram_scraper
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANDROID_HOST=android
      - ANDROID_PORT=4723
      - ANDROID_DEVICE_NAME=Nexus 5
    depends_on:
      postgres:
        condition: service_healthy
      android:
        condition: service_started
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - ./shared:/app/shared
      - ./uploads:/app/uploads
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev:
  android_data:

networks:
  default:
    name: instagram_scraper_dev_network
