services:
  postgres:
    image: postgres:15
    container_name: instagram_scraper_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: instagram_scraper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  android:
    image: budtmo/docker-android:emulator_11.0
    container_name: android_emulator
    privileged: true
    restart: unless-stopped
    ports:
      - "6080:6080"
      - "4723:4723"
      - "5554:5554" 
      - "5555:5555"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
      - APPIUM=true
      - RELAXED_SECURITY=true
      - DATAPARTITION=1024m
      - AUTO_RECORD=false
      - CONNECT_TO_GRID=false
      - MOBILE_WEB_TEST=false
      - LOG_WEB_SHARED=false
    volumes:
      - ./apks:/apks
      - android_data:/home/androidusr
    devices:
      - /dev/kvm:/dev/kvm
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:6080 && adb devices | grep -q emulator"]
      interval: 60s
      timeout: 20s
      retries: 10
      start_period: 300s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    shm_size: 2g
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram_scraper_app_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/instagram_scraper
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANDROID_HOST=android
      - ANDROID_PORT=4723
    depends_on:
      postgres:
        condition: service_healthy
      android:
        condition: service_started
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - ./shared:/app/shared
      - ./uploads:/app/uploads
      - /app/node_modules
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_dev:
  android_data:

networks:
  default:
    name: instagram_scraper_dev_network